W_r_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: Wrist_rotation
    joint_speed: 1.0
    motor:
        id: 41
        init: 2048
        min: 0
        max: 4096
        
W_a_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: Wrist_adduction
    joint_speed: 1.0
    motor:
        id: 42
        init: 2048
        min: 0
        max: 4096

W_f_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: Wrist_flexion
    joint_speed: 1.0
    motor:
        id: 43
        init: 2048
        min: 0
        max: 4096

Th_a_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: Thumb_adduction
    joint_speed: 1.0
    motor:
        id: 44
        init: 2048
        min: 0
        max: 4096

Th_f_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: Thumb_flexion
    joint_speed: 1.0
    motor:
        id: 45
        init: 2048
        min: 0
        max: 4096

I_f_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: Index_flexion
    joint_speed: 1.0
    motor:
        id: 46
        init: 2048
        min: 0
        max: 4096

M_f_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: Middle_flexion
    joint_speed: 1.0
    motor:
        id: 47
        init: 2048
        min: 0
        max: 4096

RL_f_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: Ring_little_flexion
    joint_speed: 1.0
    motor:
        id: 48
        init: 2048
        min: 0
        max: 4096
